services:
  todo_backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - .:/app
    depends_on:
      - db
    command: ["go", "run", "./cmd/app/main.go"]
  db:
    image: postgres:16.4
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: local
      POSTGRES_USER: manager
    volumes:
      - db-store:/var/lib/postgres
  postgresdef:
    build:
      context: ./sql/
      dockerfile: Dockerfile
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=manager
      - POSTGRES_PASSWORD=password
      - POSTGRES_DATABASE=local

volumes:
  db-store:
